---
- name: add distribution-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: add backports repository
  apt_repository:
    repo: 'deb {{ backports_uri }} {{ backports_components }}'
    filename: "{{ backports_filename | d(omit) }}"
    state: present
    update_cache: yes
